### ISSUE TITLE
EVE-KILL support?

### ISSUE THREAD

**Issue by KongGal** [SvenBrnn/hazardous-killbot#14]
Possible to add eve-kill support?  
https://eve-kill.com/docs/apidocs

**Comment by SvenBrnn** [comment]
Sorry, i cannot see anything that would make that possible.
For zkillboard i am using the webhook subscription. I cannot see anything equal for eve-kill.

**Comment by KongGal** [comment]
There is https://eve-kill.com/docs/stomp
